# Описываем сервисы, которые будет запускать Docker Compose
services:
  # Имя сервиса
  bot:
    # Собрать образ из текущей папки
    build: .

    # Имя контейнера
    container_name: weather-bot

    # Подключить переменные окружения из файла .env
    env_file:
      - .env

    # Автоматически перезапускать контейнер,
    # если он остановился с ошибкой или после перезагрузки
    restart: unless-stopped
    