#!/usr/bin/env python3

print('HI')


word= str(input('Вставь текст ')) #получаем тект 

print('напиши не число')

da1=word.count('-')-word.count('--')
da=0 # переменая для знаков
symbols = ['[','/','?','_',  ",", ".", ";", ":", "'", '"', "-", "(", ")"] # список со знаками 
for i in range(len(symbols)):
	da+=word.count(symbols[i]) #проходимся по списку и ищем знаки


sym= len(word)-word.count(' ') #считаем символы и вычитаем пробелы


#вывод
print(f'знаков: {da}') #вывод знаков
print(f"символов: {sym - da}") #вывод символов
print(f"Количество слов: {word.count(' ') + 1 - da1}") #вывод сколько слов в тексте	

	

